# Generated by Django 3.1.7 on 2021-04-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StarObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('object_type', models.CharField(max_length=100, verbose_name='Object type')),
                ('mass_kg', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='Mass in kg')),
                ('radius_km', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='Radius in km')),
                ('density_gcm3', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='Density in g/cm3')),
                ('rotation_period_days', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='Rotation period in days')),
                ('temperature_kelvin', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='Temperature in Kelvins')),
                ('type_of_star', models.CharField(max_length=10, verbose_name='Type of star')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
