# Generated by Django 3.1.7 on 2021-04-05 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('astronomical_objects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='starobject',
            name='age',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=20, verbose_name='Age of the star'),
        ),
        migrations.AddField(
            model_name='starobject',
            name='declination_d',
            field=models.SmallIntegerField(default=None, verbose_name='Degrees of declination'),
        ),
        migrations.AddField(
            model_name='starobject',
            name='declination_m',
            field=models.PositiveSmallIntegerField(default=None, verbose_name='Minutes of declination'),
        ),
        migrations.AddField(
            model_name='starobject',
            name='declination_s',
            field=models.DecimalField(decimal_places=8, default=None, max_digits=10, verbose_name='Seconds of declination'),
        ),
        migrations.AddField(
            model_name='starobject',
            name='description_of_type',
            field=models.CharField(default=None, max_length=50, verbose_name="Description of star's type"),
        ),
        migrations.AddField(
            model_name='starobject',
            name='distance_to_the_sun_ly',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=18, verbose_name='Distance to the sun in light years'),
        ),
        migrations.AddField(
            model_name='starobject',
            name='known_planets',
            field=models.PositiveSmallIntegerField(default=None, verbose_name='Known planets'),
        ),
        migrations.AddField(
            model_name='starobject',
            name='right_ascension_h',
            field=models.PositiveSmallIntegerField(default=None, verbose_name='Hours of right ascension'),
        ),
        migrations.AddField(
            model_name='starobject',
            name='right_ascension_m',
            field=models.PositiveSmallIntegerField(default=None, verbose_name='Minutes of right ascension'),
        ),
        migrations.AddField(
            model_name='starobject',
            name='right_ascension_s',
            field=models.DecimalField(decimal_places=8, default=None, max_digits=10, verbose_name='Seconds of right ascension'),
        ),
        migrations.AlterField(
            model_name='starobject',
            name='density_gcm3',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=18, verbose_name='Density in g/cm3'),
        ),
        migrations.AlterField(
            model_name='starobject',
            name='mass_kg',
            field=models.DecimalField(decimal_places=8, default=None, max_digits=50, verbose_name='Mass in kg'),
        ),
        migrations.AlterField(
            model_name='starobject',
            name='name',
            field=models.CharField(default=None, max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='starobject',
            name='object_type',
            field=models.CharField(default=None, max_length=100, verbose_name='Object type'),
        ),
        migrations.AlterField(
            model_name='starobject',
            name='radius_km',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=18, verbose_name='Radius in km'),
        ),
        migrations.AlterField(
            model_name='starobject',
            name='rotation_period_days',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=18, verbose_name='Rotation period in days'),
        ),
        migrations.AlterField(
            model_name='starobject',
            name='temperature_kelvin',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=18, verbose_name='Temperature in Kelvins'),
        ),
        migrations.AlterField(
            model_name='starobject',
            name='type_of_star',
            field=models.CharField(default=None, max_length=10, verbose_name='Type of star'),
        ),
        migrations.CreateModel(
            name='NotStarObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100, verbose_name='Name')),
                ('object_type', models.CharField(default=None, max_length=100, verbose_name='Object type')),
                ('mass_kg', models.DecimalField(decimal_places=8, default=None, max_digits=50, verbose_name='Mass in kg')),
                ('radius_km', models.DecimalField(decimal_places=6, default=None, max_digits=18, verbose_name='Radius in km')),
                ('density_gcm3', models.DecimalField(decimal_places=6, default=None, max_digits=18, verbose_name='Density in g/cm3')),
                ('rotation_period_days', models.DecimalField(decimal_places=6, default=None, max_digits=18, verbose_name='Rotation period in days')),
                ('temperature_kelvin', models.DecimalField(decimal_places=6, default=None, max_digits=18, verbose_name='Temperature in Kelvins')),
                ('known_satellites', models.PositiveSmallIntegerField(default=None, verbose_name='Known satellites')),
                ('aphelion_km', models.DecimalField(decimal_places=6, default=None, max_digits=18, verbose_name='Aphelion in km')),
                ('perihelion_km', models.DecimalField(decimal_places=6, default=None, max_digits=18, verbose_name='Perihelion in km')),
                ('semi_major_axis_km', models.DecimalField(decimal_places=6, default=None, max_digits=18, verbose_name='Semi-major axis in km')),
                ('orbital_period_days', models.DecimalField(decimal_places=6, default=None, max_digits=18, verbose_name='Orbital period in days')),
                ('eccentricity', models.DecimalField(decimal_places=10, default=None, max_digits=12, verbose_name='Eccentricity')),
                ('inclination', models.DecimalField(decimal_places=10, default=None, max_digits=14, verbose_name='Inclination')),
                ('argument_of_perihelion', models.DecimalField(decimal_places=10, default=None, max_digits=14, verbose_name='Argument of perihelion')),
                ('longitude_of_ascending_node', models.DecimalField(decimal_places=10, default=None, max_digits=14, verbose_name='Longitude of ascending node')),
                ('mean_anomaly', models.DecimalField(decimal_places=10, default=None, max_digits=14, verbose_name='Mean anomaly')),
                ('albedo', models.DecimalField(decimal_places=6, default=None, max_digits=8, verbose_name='Albedo')),
                ('orbital_parent', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='astronomical_objects.starobject')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
